# https://gohugo.io/host-and-deploy/host-on-cloudflare/
name = "highlyflammable-homepage"
compatibility_date = "2025-07-31"

[[routes]]
pattern = "highlyflammable.tech"
custom_domain = true

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
